// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64"

open Syntax

type token = 
  | IDENT of string
  | TYPE_LITERAL of string
  | HEADER of string
  | CODE of string
  | BAR
  | PERCENT_PERCENT
  | START
  | KW_TYPE
  | TOKEN
  | LEFT
  | RIGHT
  | NONASSOC
  | COLON
  | PREC
  | SEMI
  | EOF

let tagOfToken (t : token) = 
  match t with
  | IDENT _ -> 0 
  | TYPE_LITERAL _ -> 1 
  | HEADER _ -> 2 
  | CODE _ -> 3 
  | BAR  -> 4 
  | PERCENT_PERCENT  -> 5 
  | START  -> 6 
  | KW_TYPE  -> 7 
  | TOKEN  -> 8 
  | LEFT  -> 9 
  | RIGHT  -> 10 
  | NONASSOC  -> 11 
  | COLON  -> 12 
  | PREC  -> 13 
  | SEMI  -> 14 
  | EOF  -> 15 

let endOfInputTag = 18 

let dataOfToken (t : token) : obj = 
  match t with 
  | IDENT x -> box x 
  | TYPE_LITERAL x -> box x 
  | HEADER x -> box x 
  | CODE x -> box x 
  | BAR  -> null 
  | PERCENT_PERCENT  -> null 
  | START  -> null 
  | KW_TYPE  -> null 
  | TOKEN  -> null 
  | LEFT  -> null 
  | RIGHT  -> null 
  | NONASSOC  -> null 
  | COLON  -> null 
  | PREC  -> null 
  | SEMI  -> null 
  | EOF  -> null 

let reductionSymbolCounts = [|1us; 5us; 1us; 0us; 2us; 0us; 1us; 0us; 3us; 3us; 2us; 2us; 2us; 2us; 2us; 0us; 2us; 1us; 6us; 1us; 0us; 1us; 0us; 3us; 1us; 3us; 2us; 0us; 2us; 0us|]
let productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 3us; 3us; 4us; 4us; 5us; 5us; 5us; 5us; 5us; 5us; 6us; 6us; 7us; 7us; 8us; 9us; 9us; 10us; 10us; 11us; 11us; 12us; 13us; 13us; 14us; 14us|]
let maxProductionBodyLength = 6
let actionTable_buckets = [| -1s; -1s; 0s; 1s; 2s; 3s; 4s; 6s; 7s; 9s; 10s; 11s; -1s; 12s; -1s; -1s; -1s; -1s; -1s; 13s; -1s; 14s; 15s; 16s; -1s; 17s; 18s; 19s; 21s; 22s; 23s; 25s; 27s; -1s; -1s; -1s; -1s; -1s; -1s; -1s; 28s; -1s; 30s; -1s; -1s; 31s; 32s; 33s; 34s; 36s; 37s; 38s; -1s; -1s; -1s; -1s; 40s; -1s; -1s; 42s; -1s; 43s; 45s; 46s; 47s; 49s; 52s; 55s; 58s; 62s; 64s; 66s; 67s; -1s; -1s; -1s; -1s; -1s; 68s; -1s; -1s; 70s; 71s; 72s; 74s; 77s; 79s; 81s; 84s; 85s; -1s; -1s; -1s; -1s; -1s; 86s; -1s; 87s; -1s; 88s; -1s; -1s; -1s; 89s; 90s; 91s; 93s; 94s; 96s; 97s; 98s; -1s; -1s; -1s; 99s; -1s; -1s; 100s; 102s; 104s; 105s; 107s; 108s; 109s; 110s; 111s; -1s; 112s; 113s; -1s; -1s |]
let actionTable_entries = [| 2s; 1s; 134s; 17s; 266s; 13s; 5s; -4s; -7s; -4s; 399s; 26s; 7s; -4s; -9s; -4s; 532s; 26s; 9s; -4s; 10s; -4s; 11s; -4s; 668s; -30s; 281s; 24s; 152s; -8s; 153s; 18s; 678s; 40s; 418s; 26s; 157s; -8s; -159s; -8s; 551s; -21s; 159s; -8s; 160s; -8s; -162s; -8s; 554s; -21s; -163s; -8s; 555s; 30s; 163s; -8s; -172s; -16s; 564s; -21s; 304s; 26s; 176s; -16s; 177s; -16s; 178s; -16s; -180s; -16s; 703s; 32s; 180s; -16s; 181s; -16s; -183s; -16s; 706s; -28s; -57s; 32767s; 449s; 29s; 190s; -16s; -324s; -16s; 716s; -28s; 62s; -6s; 63s; -6s; -65s; -6s; 195s; -16s; -66s; -6s; -197s; -16s; 589s; 32s; -67s; -6s; -198s; -16s; 328s; -16s; -68s; -6s; -199s; -16s; 329s; -16s; -69s; -6s; -200s; -16s; -331s; -16s; 592s; -28s; -201s; -16s; 331s; -16s; -202s; -16s; 332s; -16s; 333s; -16s; 334s; -16s; -210s; -16s; 602s; -28s; 81s; 5s; 82s; 6s; -84s; 7s; 214s; -16s; -85s; 8s; -216s; -16s; 608s; 32s; -86s; 9s; 216s; -16s; -87s; 10s; 217s; -16s; -88s; 11s; -219s; -16s; 611s; -28s; 219s; -16s; 220s; -16s; 95s; 13s; 621s; -28s; 361s; -16s; 627s; -23s; 366s; -16s; -368s; -16s; 760s; 43s; 368s; -16s; -370s; -16s; 631s; 37s; 370s; -16s; 371s; -16s; 372s; -16s; 114s; -16s; -249s; 18s; 641s; 38s; -381s; 26s; 642s; -23s; 119s; -16s; -121s; -16s; 513s; 26s; 121s; -16s; 122s; -16s; 123s; -16s; 124s; -16s; 125s; -16s; 782s; 44s; 259s; -8s |]
let actionTable_defaultActions = [| -32768s; -3s; -1s; -32768s; -32768s; -32768s; -32768s; -32768s; -32768s; -32768s; -32768s; -32768s; -5s; -32768s; -32768s; -18s; -11s; -32768s; -7s; -32768s; -12s; -13s; -14s; -32768s; -2s; -17s; -15s; -10s; -9s; -32768s; -20s; -32768s; -32768s; -32768s; -25s; -32768s; -27s; -32768s; -22s; -19s; -32768s; -32768s; -24s; -29s; -26s |]
let gotoTable_buckets = [| 0s; 2s; 4s; -1s; -1s; -1s; -1s; 5s; 6s; 7s; -1s; 9s; 10s; 12s; 13s; 14s; 15s; 16s; -1s; 18s; -1s; -1s; -1s; -1s; 19s; 20s; 23s; -1s; -1s |]
let gotoTable_entries = [| -262s; 27s; 493s; 36s; -2s; 2s; 291s; 28s; 2s; 3s; 65s; 12s; 124s; 19s; -97s; 16s; 444s; 31s; 156s; 21s; -477s; 33s; 505s; 39s; 477s; 34s; 478s; 35s; 218s; 25s; 567s; 42s; -540s; 41s; 568s; 35s; 48s; 4s; 82s; 14s; -84s; 15s; -142s; 20s; 199s; 23s; 171s; 22s |]
let reductions =    [| 
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Syntax.ParserSpec)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      failwith "unreachable"
                   )
                 : '_startspec));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'headerOpt)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'decls)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'rules)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                                                       { Header = _1; Decls = List.rev _2; Rules = List.rev _4 } 
                   )
                 : Syntax.ParserSpec));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                    _1 
                   )
                 : 'headerOpt));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                    "" 
                   )
                 : 'headerOpt));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'decls)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'decl)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                        _2 :: _1 
                   )
                 : 'decls));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                        [] 
                   )
                 : 'decls));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                          Some _1 
                   )
                 : 'optTypeLiteral));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                          None 
                   )
                 : 'optTypeLiteral));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'optTypeLiteral)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'idents)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                                           Token (_2, List.rev _3) 
                   )
                 : 'decl));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'idents)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                                         Type (_2, List.rev _3) 
                   )
                 : 'decl));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'idents)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                                         Start (List.rev _2) 
                   )
                 : 'decl));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'idents)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                                         Prec (LeftAssoc, List.rev _2) 
                   )
                 : 'decl));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'idents)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                                         Prec (RightAssoc, List.rev _2) 
                   )
                 : 'decl));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'idents)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                                         Prec (NonAssoc, List.rev _2) 
                   )
                 : 'decl));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'idents)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                          _2 :: _1 
                   )
                 : 'idents));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                          [] 
                   )
                 : 'idents));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rules)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'rule)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                        _2 :: _1 
                   )
                 : 'rules));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rule)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                        [_1] 
                   )
                 : 'rules));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'optTypeLiteral)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'optbar)) in
            let _5 = (let data = parseState.GetInput(5) in (Microsoft.FSharp.Core.Operators.unbox data : 'clauses)) in
            let _6 = (let data = parseState.GetInput(6) in (Microsoft.FSharp.Core.Operators.unbox data : 'optsemi)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                                                               (_1, _2, List.rev _5) 
                   )
                 : 'rule));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                 
                   )
                 : 'optbar));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                 
                   )
                 : 'optbar));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                  
                   )
                 : 'optsemi));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                  
                   )
                 : 'optsemi));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'clauses)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'clause)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                                _3 :: _1 
                   )
                 : 'clauses));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'clause)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                                [_1] 
                   )
                 : 'clauses));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'syms)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'optprec)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                               { Symbols = _1; PrecSymbol = _2; Code = _3} 
                   )
                 : 'clause));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'syms)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                        _1 :: _2 
                   )
                 : 'syms));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                        [] 
                   )
                 : 'syms));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                        Some _2 
                   )
                 : 'optprec));
        (fun (parseState : FsLexYaccLiteRuntime.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                                        None 
                   )
                 : 'optprec));
|]
let terminalsCount = 19
let nonTerminalsCount = 15
let tables = FsLexYaccLiteRuntime.ParseTables(reductions, endOfInputTag, tagOfToken, dataOfToken, reductionSymbolCounts, productionToNonTerminalTable, maxProductionBodyLength, gotoTable_buckets, gotoTable_entries, nonTerminalsCount, actionTable_buckets, actionTable_entries, actionTable_defaultActions, terminalsCount)
let spec lexer lexbuf : Syntax.ParserSpec = unbox (tables.Interpret(lexer, lexbuf, 0))
