// Implementation file for parser generated by fsyacc
module Test.Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "Parser.fsy"

open Test.Ast

# 10 "Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | ELSE
  | THEN
  | IF
  | DOTDOT
  | STAR
  | MINUS
  | PLUS
  | NUMBER of (int)
  | IDENT of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_ELSE
    | TOKEN_THEN
    | TOKEN_IF
    | TOKEN_DOTDOT
    | TOKEN_STAR
    | TOKEN_MINUS
    | TOKEN_PLUS
    | TOKEN_NUMBER
    | TOKEN_IDENT
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startExpr
    | NONTERM_Expr

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | ELSE  -> 1 
  | THEN  -> 2 
  | IF  -> 3 
  | DOTDOT  -> 4 
  | STAR  -> 5 
  | MINUS  -> 6 
  | PLUS  -> 7 
  | NUMBER _ -> 8 
  | IDENT _ -> 9 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_ELSE 
  | 2 -> TOKEN_THEN 
  | 3 -> TOKEN_IF 
  | 4 -> TOKEN_DOTDOT 
  | 5 -> TOKEN_STAR 
  | 6 -> TOKEN_MINUS 
  | 7 -> TOKEN_PLUS 
  | 8 -> TOKEN_NUMBER 
  | 9 -> TOKEN_IDENT 
  | 12 -> TOKEN_end_of_input
  | 10 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startExpr 
    | 1 -> NONTERM_Expr 
    | 2 -> NONTERM_Expr 
    | 3 -> NONTERM_Expr 
    | 4 -> NONTERM_Expr 
    | 5 -> NONTERM_Expr 
    | 6 -> NONTERM_Expr 
    | 7 -> NONTERM_Expr 
    | 8 -> NONTERM_Expr 
    | 9 -> NONTERM_Expr 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 12 
let _fsyacc_tagOfErrorTerminal = 10

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | ELSE  -> "ELSE" 
  | THEN  -> "THEN" 
  | IF  -> "IF" 
  | DOTDOT  -> "DOTDOT" 
  | STAR  -> "STAR" 
  | MINUS  -> "MINUS" 
  | PLUS  -> "PLUS" 
  | NUMBER _ -> "NUMBER" 
  | IDENT _ -> "IDENT" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | ELSE  -> (null : System.Object) 
  | THEN  -> (null : System.Object) 
  | IF  -> (null : System.Object) 
  | DOTDOT  -> (null : System.Object) 
  | STAR  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | NUMBER _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | IDENT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 9us; 65535us; 0us; 1us; 12us; 4us; 13us; 5us; 14us; 6us; 15us; 7us; 16us; 8us; 17us; 9us; 18us; 10us; 19us; 11us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 5us; 0us; 3us; 4us; 5us; 6us; 1us; 1us; 1us; 2us; 5us; 3us; 3us; 4us; 5us; 6us; 5us; 3us; 4us; 4us; 5us; 6us; 5us; 3us; 4us; 5us; 5us; 6us; 5us; 3us; 4us; 5us; 6us; 6us; 5us; 3us; 4us; 5us; 6us; 7us; 6us; 3us; 4us; 5us; 6us; 8us; 9us; 6us; 3us; 4us; 5us; 6us; 8us; 9us; 5us; 3us; 4us; 5us; 6us; 8us; 1us; 3us; 1us; 4us; 1us; 5us; 1us; 6us; 1us; 7us; 2us; 8us; 9us; 2us; 8us; 9us; 1us; 8us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 8us; 10us; 12us; 18us; 24us; 30us; 36us; 42us; 49us; 56us; 62us; 64us; 66us; 68us; 70us; 72us; 75us; 78us; |]
let _fsyacc_action_rows = 20
let _fsyacc_actionTableElements = [|4us; 32768us; 3us; 17us; 6us; 16us; 8us; 3us; 9us; 2us; 4us; 49152us; 4us; 15us; 5us; 14us; 6us; 13us; 7us; 12us; 0us; 16385us; 0us; 16386us; 1us; 16387us; 5us; 14us; 1us; 16388us; 5us; 14us; 0us; 16389us; 3us; 16390us; 5us; 14us; 6us; 13us; 7us; 12us; 0us; 16391us; 5us; 32768us; 2us; 18us; 4us; 15us; 5us; 14us; 6us; 13us; 7us; 12us; 5us; 16393us; 1us; 19us; 4us; 15us; 5us; 14us; 6us; 13us; 7us; 12us; 4us; 16392us; 4us; 15us; 5us; 14us; 6us; 13us; 7us; 12us; 4us; 32768us; 3us; 17us; 6us; 16us; 8us; 3us; 9us; 2us; 4us; 32768us; 3us; 17us; 6us; 16us; 8us; 3us; 9us; 2us; 4us; 32768us; 3us; 17us; 6us; 16us; 8us; 3us; 9us; 2us; 4us; 32768us; 3us; 17us; 6us; 16us; 8us; 3us; 9us; 2us; 4us; 32768us; 3us; 17us; 6us; 16us; 8us; 3us; 9us; 2us; 4us; 32768us; 3us; 17us; 6us; 16us; 8us; 3us; 9us; 2us; 4us; 32768us; 3us; 17us; 6us; 16us; 8us; 3us; 9us; 2us; 4us; 32768us; 3us; 17us; 6us; 16us; 8us; 3us; 9us; 2us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 5us; 10us; 11us; 12us; 14us; 16us; 17us; 21us; 22us; 28us; 34us; 39us; 44us; 49us; 54us; 59us; 64us; 69us; 74us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 1us; 3us; 3us; 3us; 3us; 2us; 6us; 4us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; |]
let _fsyacc_immediateActions = [|65535us; 65535us; 16385us; 16386us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; |]
let _fsyacc_reductions ()  =    [| 
# 129 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startExpr));
# 138 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "Parser.fsy"
                                                         Ident _1 
                   )
# 29 "Parser.fsy"
                 : Test.Ast.Expr));
# 149 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "Parser.fsy"
                                                      Number _1 
                   )
# 30 "Parser.fsy"
                 : Test.Ast.Expr));
# 160 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 31 "Parser.fsy"
                                                         Add (_1, _3) 
                   )
# 31 "Parser.fsy"
                 : Test.Ast.Expr));
# 172 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "Parser.fsy"
                                                         Sub (_1, _3) 
                   )
# 32 "Parser.fsy"
                 : Test.Ast.Expr));
# 184 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "Parser.fsy"
                                                         Mult (_1, _3) 
                   )
# 33 "Parser.fsy"
                 : Test.Ast.Expr));
# 196 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "Parser.fsy"
                                                         Range (_1, _3) 
                   )
# 34 "Parser.fsy"
                 : Test.Ast.Expr));
# 208 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "Parser.fsy"
                                                      Neg _2 
                   )
# 35 "Parser.fsy"
                 : Test.Ast.Expr));
# 219 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            let _6 = (let data = parseState.GetInput(6) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "Parser.fsy"
                                                      If (_2, _4, Some _6) 
                   )
# 36 "Parser.fsy"
                 : Test.Ast.Expr));
# 232 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : Test.Ast.Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "Parser.fsy"
                                                      If (_2, _4, None) 
                   )
# 37 "Parser.fsy"
                 : Test.Ast.Expr));
|]
# 245 "Parser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 13;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let Expr lexer lexbuf : Test.Ast.Expr =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
